export const GET_IMAGES = 'GET_IMAGES';
export const GETTING_IMAGES = 'GETTING_IMAGES';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_CURRENT_IMG_BLOB = 'SET_CURRENT_IMG_BLOB';
export const EMPTY_IMAGES = 'EMPTY_IMAGES';
